services:
  frontend:
    depends_on:
      - backend
    image: ${ECR_FRONTEND_REPO_URI}
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: always
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "export INFISICAL_API_URL='https://${INFISICAL_REGION}.infisical.com' && infisical run --token=$(infisical login --method=universal-auth --client-id=${INFISICAL_CLIENT_ID} --client-secret=${INFISICAL_CLIENT_SECRET} --silent --plain) --env=${INFISICAL_ENV} --projectId=${INFISICAL_PROJECT_ID} --path=/frontend -- ${FRONTEND_BUILD_COMMAND}",
      ]
    networks:
      - app-network

  backend:
    container_name: backend
    image: ${ECR_BACKEND_REPO_URI}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: "always"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "export INFISICAL_API_URL='https://${INFISICAL_REGION}.infisical.com' && infisical run --token=$(infisical login --method=universal-auth --client-id=${INFISICAL_CLIENT_ID} --client-secret=${INFISICAL_CLIENT_SECRET} --silent --plain) --env=${INFISICAL_ENV} --projectId=${INFISICAL_PROJECT_ID} --path=/backend -- ${BACKEND_BUILD_COMMAND}",
      ]
    # Uncomment them if you're on firebase boilerplate
    # volumes:
    #   - './firebase-cert.json:/app/lib/firebase-cert.json'
    networks:
      - app-network

  worker:
    container_name: worker
    image: ${ECR_BACKEND_REPO_URI}
    ports:
      - "${WORKER_PORT}:${WORKER_PORT}"
    restart: "always"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "export INFISICAL_API_URL='https://${INFISICAL_REGION}.infisical.com' && infisical run --token=$(infisical login --method=universal-auth --client-id=${INFISICAL_CLIENT_ID} --client-secret=${INFISICAL_CLIENT_SECRET} --silent --plain) --env=${INFISICAL_ENV} --projectId=${INFISICAL_PROJECT_ID} --path=/backend -- ${WORKER_BUILD_COMMAND}",
      ]
    # Uncomment them if you're on firebase boilerplate
    # volumes:
    #   - './firebase-cert.json:/app/lib/firebase-cert.json'
    networks:
      - app-network

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/data
    ports:
      - ${DOZZLE_PORT}:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_ENABLE_SHELL: false

networks:
  app-network:
    driver: bridge
